open-sauced/pizza-cli

- cmd/repo-query/repo-query.go
- cmd/root/root.go
Fixes #14 
#14 
Implemented a loop for QnA after I recorded this GIF.
> feat: repo-query support

- .github/workflows/release.yaml
This uploads Go artifacts to the GitHub release after its been created.
You can see this worked from tests in my fork: https://github.com/jpmcb/pizza-cli/releases/tag/v0.0.1
Related to #19 
N/a
> feat: GitHub action to build and upload Go artifacts after release created

- .github/workflows/release.yaml
Fixes missing generated token during CI release action.
Includes some whitespace fixes.
Related to https://github.com/open-sauced/pizza-cli/issues/35#issuecomment-1691901233 (cc @Anush008)
> As a result, it defaults to the default GITHUB_TOKEN credential. I think this is causing an issue with the @semantic-release/git plugin, as this credential does not have the required permission to operate on protected branches.
> fix: Uses correct generated token when checking out cli repo in release

- cmd/show/contributors.go
This PR adds a calculation to get the correct pull request velocity percentage to display. It calculates the percentage with the same formula implemented by the```getPercent(total, count)``` method. This approach is used in ```dev-card``` component via ```getPercent(prTotal, mergedPrs)``` to render the percentage in the ```VelocityPill```.
https://github.com/open-sauced/app/blob/5b15a49d6dfbd371799d7dbf81cd5cbfef5e1d60/lib/utils/get-percent.ts#L1
Fixes #45
> fix: add calculation to display correct pull request velocity

- cmd/insights/contributors.go
- pkg/constants/output.go
This PR adds the csv output support for ```pizza insights contributors [url]``` command.
#42 Feature: Support --output/-o flag globally for yaml, json, and csv outputs
> feat: add csv support for contributors insights

- cmd/insights/contributors.go
- cmd/insights/repositories.go
- cmd/repo-query/repo-query.go
- cmd/root/root.go
- pkg/constants/templates.go
This is a sort of grab bag PR with a few small fixes I've been wanting to get in, primarily around user experience, styling, and text copy
Closes #48
> chore: cleaning up some copy and general UX flow

- cmd/insights/user-contributions.go
Followup to #58 
Adds filtering for users on the `user-contributions` command
```
❯ ./build/pizza insights user-contributions \
https://github.com/open-sauced/api \
https://github.com/open-sauced/app \
--users jpmcb,brandonroberts
https://github.com/open-sauced/api
User           Total      Commits    PRs Created
brandonroberts 4          0          4
jpmcb          5          0          5
https://github.com/open-sauced/app
User           Total      Commits    PRs Created
brandonroberts 368        334        34
jpmcb          6          5          1
```
Closes #57 - decided against adding a whole extra command since this actually gets us pretty close by just adding a filter. Can continue to iterate based on feedback.
> feat: Add filtering for usernames on user-contributions

- cmd/insights/user-contributions.go
This PR adds the ```sort``` flag to be able to sort the output of ```insights user-contributions``` command. Options to sort include (total, commits, prs).
Example (prs)
```bash
open-sauced/app
User                Total      Commits    PRs Created     
brandonroberts      328        299        29              
OgDev-01            175        146        29              
nickytonline        183        162        21              
5hraddha            47         40         7               
RitaDee             46         39         7               
itskish0re          14         9          5               
Satoshi-Sh          6          3          3               
shelar1423          6          3          3               
aryanas159          26         24         2               
brainconnect93 …
```
> feat: Add sort capabilities to user contributions

- cmd/insights/contributors.go
- pkg/api/validation.go
This PR adds a range validation to the ```insights contributors``` command. It will check for the value of the period flag. In case the period provided is invalid, it returns a descriptive error to signal that the API only accepts (7,30,90) as period values.
Before
```bash 
$ pizza insights contributors open-sauced/app -p 45
Error: error while calling 'ContributorsServiceAPI.FindAllRecentPullRequestContributors' with repository 501028599': 400 Bad Request
error while calling 'ContributorsServiceAPI.FindAllRepeatPullRequestContributors' with repository 501028599: 400 Bad Request
error while calling 'ContributorsServiceAPI.FindAllChurnPullRequestContributors' with repository 501028599': 400 Bad Request
error while calling 'ContributorsServiceAPI.NewPullRequestContributors' with repository …
```
> fix: validate period flag

- .github/workflows/release.yaml
- Makefile
If your system doesn't have the `gcc` installed, the binary won't get built.
This PR fixes #70 
Try deleting gcc `sudo apt-get --purge remove gcc` and running `make build`
Make sure the CI passes (didn't test the workflow)
> fix: avoid requiring CGO for now

- cmd/auth/constants.go
This PR updates the supabase keys for auth, 
#79
> fix: update supabase keys for auth

- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/ISSUE_TEMPLATE/config.yaml
- .github/ISSUE_TEMPLATE/feature_request.yaml
These are pizza CLI specific issue templates (which importantly include automatically adding the `pizza-cli` label to issues)
> chore: Include pizza cli specific issue templates

- go.mod
Small change to upgrade the Go module to Go 1.22
N/a
Able to `just build-all`
> feat: Upgrade Go module to use Go 1.22

- Dockerfile
- cmd/version/version.go
- justfile
- pkg/utils/version.go
Adds built at time to the pizza `version` command.
Closes #86
N/A
1. Run `just install`.
2. Run `pizza version`.
3. Notice the build date in the version now.
```
❯ pizza version
Version: dev
Sha: HEAD
Built at: 2024-08-26 20:10:06
```
4. Run `just build-all`.
5. Everything compiles still for all build targets.
> feat: added built at to version command

- cmd/generate/codeowners/output.go
- cmd/generate/codeowners/output_test.go
- Escapes non-standard characters in the filepath with a `\` when generating a CODEOWNERS file
- Also splits the filename in case its a rename, in reference to #101. Not the recommended fix, but a workaround for now. 
Closes #100
1. Open `cmd/generate/codeowners/output_test.go` and inspect test file
2. Run `just test`
> fix: escape non-standard characters in the filename path

- cmd/insights/insights.go
- cmd/root/root.go
- Moves `output` flag under `insights` command
Fixes #104
> fix: move output flag to insights command

- cmd/root/root.go
Root command now correctly marks persistent flags as hidden. It was giving:
```
❯ ./build/pizza
2024/08/30 11:01:05 error marking endpoint as hidden: flag "endpoint" does not exist
```
Followup to #113 
1. Build via `just build`
2. Run with `./build/pizza` and output is corrected
> fix: Root command persistent flags are marked hidden correctly

- cmd/generate/codeowners/codeowners.go
- cmd/generate/codeowners/output.go
Updates the `CODEOWNERS` copy with the command that generated it with flags.
Closes #118
> feat: update `CODEOWNERS` copy with command

- api/auth/auth.go
- api/client.go
- api/services/workspaces/spec.go
- api/services/workspaces/userlists/spec.go
- api/services/workspaces/userlists/userlists.go
- api/services/workspaces/userlists/userlists_test.go
- api/services/workspaces/workspaces.go
- api/services/workspaces/workspaces_test.go
- cmd/generate/codeowners/codeowners.go
- pkg/config/config_test.go
Implements a loop-back user flow for connecting discovered codeowners with the OpenSauced platform. This will ask if the user wants to create a Contributor Insight and makes the necessary API calls to make that happen.
Closes #https://github.com/open-sauced/pizza-cli/issues/99
Example workflow:
```
❯ ./build/pizza generate codeowners . -l debug
Built logger with log level: 4
Opened repo at: /Users/jpmcb/workspace/opensauced/pizza-cli
Looking back 90 days
Finished processing commits for: /Users/jpmcb/workspace/opensauced/pizza-cli
Processing codeowners file at: /Users/jpmcb/workspace/opensauced/pizza-cli/CODEOWNERS
Finished generating file: /Users/jpmcb/workspace/opensauced/pizza-cli/CODEOWNERS
Do you want to add these codeowners to an OpenSauced Contributor Insight? (y/n): y
Adding …
```
> feat: Create a contributor list after generating codeowners

- .env
- .github/workflows/test.yaml
- Dockerfile
- cmd/auth/auth.go
- cmd/generate/codeowners/codeowners.go
- cmd/insights/contributors.go
- cmd/insights/repositories.go
- justfile
- pkg/utils/posthog.go
This PR does the following:
- Exhumes the posthog reporting including the buildtime variable. The justfile loads the posthog public API key from the new `.env`
- closes: https://github.com/open-sauced/pizza-cli/issues/125
- Adds posthog capturing for codeowners generate commands and insight commands
- Introduces a `just help` command to get a list of all commands (and their descriptions)
- closes: https://github.com/open-sauced/pizza-cli/issues/119
- Upgrades golangci-lint to `golangci-lint:v1.60`
1. Build locally
2. For the core engineering team, you can log in and see the events being captured by the CLI
> fix: Revive Posthog's write only key

- .golangci.yaml
- api/auth/auth.go
- api/services/contributors/contributors.go
- api/services/contributors/contributors_test.go
- api/services/histogram/histogram.go
- api/services/histogram/histogram_test.go
- api/services/repository/repository.go
- api/services/repository/repository_test.go
- api/services/workspaces/userlists/userlists.go
- api/services/workspaces/userlists/userlists_test.go
- api/services/workspaces/workspaces.go
- api/services/workspaces/workspaces_test.go
- cmd/generate/codeowners/codeowners.go
- cmd/generate/codeowners/output_test.go
- cmd/insights/contributors.go
- cmd/insights/user-contributions.go
- pkg/config/config_test.go
Adds a few more linters and corrects the code where linters have now errored.
Closes: https://github.com/open-sauced/pizza-cli/issues/124
`just lint` works
> chore: Adds additional linters and enforces stricter rules

- .gitignore
- cmd/docs/docs.go
- cmd/docs/docs_test.go
- cmd/root/root.go
- docs/pizza.md
- docs/pizza_completion.md
- docs/pizza_completion_bash.md
- docs/pizza_completion_fish.md
- docs/pizza_completion_powershell.md
- docs/pizza_completion_zsh.md
- docs/pizza_generate.md
- docs/pizza_generate_codeowners.md
- docs/pizza_insights.md
- docs/pizza_insights_contributors.md
- docs/pizza_insights_repositories.md
- docs/pizza_insights_user-contributions.md
- docs/pizza_login.md
- docs/pizza_version.md
- go.mod
- go.sum
Now the documentation for the pizza-cli can be generated via the `docs` command, e.g. `pizza docs`. By default if no path is specified, the default path, `"./docs"` will be used.
Closes #120
1. Run `just build`
2. Run `./build/pizza docs`
3. Notice docs get generated in the `./docs` folder.
4. Run `./build pizza docs ./docs2`.
5. Notice docs get generated in the `./docs2` folder.
> feat: now the documentation for the pizza-cli can be generated via pizza docs

- justfile
- pkg/utils/root.go
- Ignores an invalid `gosec` lint error
- Adds a few nice to have `just` commands:
- `just gen-docs` re-generates the docs into the `./docs/` directory
- `just dev` runs all the common dev commands
- `just install-dev-tools` installs the necessary, third party dev tools (right now, just `goimports`
Followup to #143 and #148 
Run the additional `just` commands
> fix: Corrects invalid gosec lint error

- cmd/generate/codeowners/codeowners.go
Now if the `--tty-disable` flag is passed to generate a codeowners, the interactive steps are skipped.
~There are currently no tests for codeowners.go. I'm going to look at adding some.~ (punting for now as mentioned below)
Closes #154
1. Run `just build`
2. Run `./build/pizza generate codeowners --tty-disable`
3. Notice the command runs and skips the interactive steps.
4. Run `./build/pizza generate codeowners`
5. Notice the command runs and does not skip the interactive steps.
> fix: skip interactive steps in generate codeowners with --tty-disable flag

- cmd/generate/codeowners/codeowners.go
- cmd/root/root.go
- pkg/config/config.go
- pkg/config/config_test.go
Uses the local `.sauced.yaml` as the default, and `~/.sauced.yaml` as the fallback location for finding the configuration file
1. Run just build
2. Go to a repo with no `.sauced.yaml` file in its root, but with a `~/.sauced.yaml` file
3. Run the codeowners generation command `pizza generate codeowners .`
4. Go to a repo with a `.sauced.yaml` file in its root
5. Run the codeowners generation command `pizza generate codeowners .`
6. Go to a repo with a `.sauced.yaml` file in its root
7. Run the codeowners generation command with a custom location `pizza generate codeowners . -c ../../.sauced.yaml`
> fix: use the local directory and home directory as fallback for .sauced.yaml

- .github/workflows/release.yaml
This pull request introduces a new job to the release workflow for automating the documentation update process before releasing a new version. Additionally, it ensures that the release process waits for the documentation update PR to be merged before proceeding.
The repository is already configured for GitHub Actions to create and approve PRs.
Closes #152
I've tested my script, but not the whole flow. We can see how it behaves for a beta release.
> chore: now docs are autogenerated as part of the release process

- cmd/auth/auth.go
- cmd/generate/codeowners/codeowners.go
- cmd/insights/contributors.go
- cmd/insights/repositories.go
- go.mod
- go.sum
- justfile
- pkg/utils/posthog.go
- pkg/utils/telemetry.go
- telemetry.go
This PR does a few things:
- Upgrades github.com/posthog/posthog-go up to v1.2.21
- Implements anonoymous user tracking with UUIDs as the `DistinctID` for events. This ID is stored locally in `~/.pizza-cli/telemetry.json`. Users can always delete this file or entirely disable telemetry via the global `--disable-telemetry` flag
- Implements a sidechain Go program (build and runable via Go's `-tags telemetry` flag) which bootstraps the events for Posthog. Why is this needed? You can't really make a dashboard in Posthog until an event has landed in the data lake. This simplifies this process by sending the events all at once to Posthog to make dashboard creation easy
- Updates the Posthog endpoint to `https://us.i.posthog.com`
- Adds error handling for each of the capture Posthog functions …
> feat: Posthog events bootstrapping

- .github/workflows/pizza.yml
Now --tty-disable is for the pizza CLI set so that the pizza-action can complete instead of hanging and failing.
Relates to #140
Relates to #141
> fix: now --tty-disable is set so the action can complete instead of hanging

- .github/workflows/release.yaml
This continues in the work in #162, however, now the docs is a separate job so it doesn't repeat itself in the build matrix job.
Fixes #161
We can try on beta again. This is a little more difficult to test on a test repo.
> fix: docs generation runs outside of build matrix now

- cmd/generate/codeowners/codeowners.go
- cmd/generate/generate.go
- cmd/generate/insight/insight.go
Refactors the existing interactive flow from `pizza generate codeowners` (after the codeowners file has been created) into its own command:
```
❯ ./build/pizza generate insight .
[jpmcb nickytonline brandonroberts zeucapua]
Do you want to add these codeowners to an OpenSauced Contributor Insight? (y/n): y
Adding codeowners to contributor insight
Access Contributor Insight on OpenSauced:
https://app.opensauced.pizza/workspaces/8718805b-66b8-4da5-887d-c37366b8e0da/contributor-insights/dfa8e053-f68a-47e9-ae09-fc13579ca4a5
```
Closes #176 
1. Build locally with `just build`
2. Run command with `./build/pizza generate insight .` in a directory with a `CODEOWNERS` file
> feat: `pizza generate insight` command

- cmd/generate/codeowners/codeowners.go
- cmd/root/root.go
- pkg/config/config.go
- pkg/config/config_test.go
Fixes problems where the local config path wasn't being used. Now, it prefers the local path over the one possibly present at home:
```
❯ ./build/pizza generate codeowners . -l debug
Built logger with log level: 4
Loaded config from: /Users/jpmcb/workspace/opensauced/pizza-cli/.sauced.yaml
```
Closes: https://github.com/open-sauced/pizza-cli/issues/180
1. Tests still pass
2. Build locally with `just build` and run with a repo that has a `.sauced.yaml`
3. Run with a repo that does not have a local `.saucedyaml` but where you do have a `~/.sauced.yaml`
> fix: Config path prefers local dir vs. home dir

- .sauced.yaml
- README.md
- cmd/generate/config/config.go
- npm/README.md
- updates readme to add info on generate config
- updates npm readme
- updates logo and project description in readmes
closes #149
> chore: update codeowners docs

- README.md
- npm/README.md
- Some updates to copy (including some command fixes that were broken)
- Moved the docker stuff into its own section
- Added a section for the pizza action
- Added explicit "Docs" section
- Elaborated some things in the "Usage" section and moved Bekah's 1.4.0 "pizza generate config" section closer to the "pizza generate codeowners" section
- Added "pizza insights" section
- Added some further context to the "Configuration Schema" section
Give it a look here since the GitHub diff is kinda gross:
https://github.com/open-sauced/pizza-cli/blob/update-readme/README.md
Followup to: #178
Closes: https://github.com/open-sauced/pizza-cli/issues/183
> feat: Update README docs

- cmd/generate/config/spec.go
Implements a new 'skip rest of emails' shortcut using `Ctrl+S` for the `pizza generate config` command in interactive mode.
Closes #177 
https://github.com/user-attachments/assets/044d00c1-6224-4fca-aae9-1c0aed970a51
1. Build the program
2. Run `pizza generate config` with the `-i`/`--interactive` flag
3. Go through a few attributions
4. Press `Ctrl+S` to skip the rest of the emails and end the program
5. Check the output `.sauced.yaml` file and see only a few you've attributed in the file
> feat: shortcut to skip rest of emails for `pizza generate config`

- README.md
Adds a quickstart guide to walk users through using the pizza-cli for their project. This includes adding a config and codeowners, generating insights and adding the GH action.
closes #202
> feat: Add quick start section

- cmd/offboard/offboard.go
- cmd/offboard/output.go
- cmd/root/root.go
- pkg/utils/posthog.go
Implements a new `pizza offboard` command that allows the user to offboard contributors from the `.sauced.yaml` config and `CODEOWNERS` files by their attributed name or email.
Closes #117 
https://github.com/user-attachments/assets/7dff36be-83dc-4ef6-af0e-6f5c1b847983
1. Build the program
2. Ensure you have the `.sauced.yaml` and `CODEOWNERS` files
3. Run `pizza offboard <usernames/emails>` with the user(s) you want to offboard
- eg: `pizza offboard zeudev john@opensauced.pizza`
4. REQUIRED: Use the `--path` (`-p`) flag to specify what repository you are updating
5. Use the `--config` (`-c`) global flag to specify the config, separate from the `--path` directory
6. After running, check the config and owners files to ensure that any attributions to the offboarded users are removed
> feat: implement `pizza offboard` command

- cmd/generate/config/output.go
Adds the following comments to the generated `.sauced.yaml` file made with the `pizza generate config` command:
```
```
Closes #170 
1. Build the CLI
2. Run `pizza generate config`
3. Read the generated `.sauced.yaml` file and see the added comments at the start
> feat: add comment preamble to generated config
