- .github/workflows/test.yaml
Adds linting, testing, and build in parallel for GitHub actions
N/a - tangentially related to https://github.com/open-sauced/pizza/pull/15
N/a
N/a
> GitHub actions: Golang actions for lint, test, build on push and PR

- cmd/bake/bake.go
This PR implements the --wait flag for the pizza-cli. When --wait is provided the client waits for processing to finish, otherwise it closes by default.
#3 implement --wait flag
> Implements --wait flag for pizza bake

- pkg/utils/help.go
This PR fixes long and short descriptions not showing when using ```-h``` or ```--help```. 
Fixes #16
> Fix: add Long and Short references to help template

- cmd/bake/bake.go
- cmd/bake/bake_test.go
- go.mod
- go.sum
This PR implements the option to batch requests to /bake which can be achieved 2 ways:
1) Variadic number of URLs, i.e, ```pizza bake https://github.com/open-sauced/pizza https://github.com/open-sauced/pizza-cli```
2) yaml file, i.e, ```pizza bake --file=config.yaml```, or using shorthand ```pizza bake -f=config.yaml```
If both options are provided, the command merges all requests and avoids duplicate requests by storing URLs in a map prior to sending the request.
#6 ability to bake many repos
> Implements the option to batch requests to /bake

- Makefile
- cmd/bake/bake.go
- cmd/bake/bake_test.go
- cmd/repo-query/repo-query.go
- cmd/root/root.go
- pkg/api/client.go
- pkg/api/constants.go
Integrates using the opensauced api client for doing "bake" operations and sets the president for using the `--beta` and `--endpoint` global flags.
Example usage:
```
❯ pizza bake --beta https://github.com/jpmcb/gopherlogs
Using beta API endpoint - https://beta.api.opensauced.pizza/v1
Resp body:
```
(note that at the time of this PR, the prod API has not merged change to normalize the requests for the `/bake` route so only the beta API is working. Use the `--beta` global flag when testing 😄 )
Related to https://github.com/open-sauced/api/issues/218
N/a
> feat: Http Client for accessing OpenSauced API client

- README.md
- install.sh
- Adds instructions for installing the `pizza` CLI
- `install.sh` script for doing the install (including instructions for safe use)
Closes #19 and is related to https://github.com/open-sauced/homebrew-tap/pull/1
N/a
> feat: Add install instructions and script for pizza CLI

- .github/workflows/release.yaml
Working on getting npm releases cut post merge and with the main branch protected, the releases will fail from outside contributors. 
The resolution is using a GITHUB_APP token similar to https://github.com/open-sauced/api/pull/239
> feat: Leverage the GITHUB_APP_TOKEN for releases

- .github/workflows/compliance.yaml
- .github/workflows/release.yaml
This PR updates the release action to 2.2.1 to include the package files bug fix added in https://github.com/open-sauced/release/pull/21.
Additionally, the PR compliance action has been added for PRs.
> ci: Update @open-sauced/release@2.2.1 and compliance.yaml

- .github/workflows/release.yaml
- README.md
- cmd/root/root.go
- cmd/version/version.go
- pkg/utils/version.go
This PR adds the `version` command which displays the release build's version metadata.
With a dummy build, this creates the following metadata into the binary
```
❯ go build -ldflags="-s -w -X 'github.com/open-sauced/pizza-cli/pkg/utils.Version=1.2.3' -X 'github.com/open-sauced/pizza-cli/pkg/utils.Sha=$(git rev-parse HEAD)'" -o build/pizza
❯ ./build/pizza version
Version: 1.2.3
Sha: 146b6b7485a0f33090a4ccefd23624f9aa0df085
```
Closes #25 
N/a
N/a
> feat: Version command for CLI based on release builds

- npm/package.json
The semantic release failed for cutting new changes into the `main` branch and releasing a new NPM package: https://github.com/open-sauced/pizza-cli/actions/runs/6476458451/job/17585204968
There is a very old `1.0.0` release already on the npm package ... so it failed with a 403 when attempting to release that new version. This patch attempts to roll forward the npm version to 1.0.1 to get semantic release to be able to publish the next version.
> fix: Roll forward fix for semantic release

- .github/workflows/release.yaml
Adds a few of the missing env vars (due to typo / missing in our github configuration) for the release pipeline to properly populate the Go buildtime variables.
> fix: Release pipeline missing some env vars

- .github/workflows/auto-add-to-project.yml
> chore: Create auto-add-to-project.yml

- .sauced.yaml
- CODEOWNERS
Adds a .sauced.yaml to the project and a regenerated OWNERS file care of `pizza generate codeowners ./ -c ./.sauced.yaml`
Closes #108
Check the PR to see if the CODEOWNERS file is value (GitHub lets you know)
> feat: added .sauced.yaml and updated CODEOWNERS file

- api/auth/success.html
Gives a style refresh on the login success page.
TODO, add the nice pizza piece background from the OpenSauced homepage.
Closes #91
**Before**
**After**
1. Open the web page api/auth/success.html in a browser
> feat: pizza login success page style refresh

- cmd/root/root.go
Closes #103 
1. Run `just build`
2. Run `./build/pizza -h`
3. Note the `beta` and `endpoint` flags are not shown
```
Usage:
pizza generate codeowners path/to/repo [flags]
Flags:
-h, --help                help for codeowners
--owners-style-file   Whether to generate an agnostic OWNERS style file.
-r, --range int           The number of days to lookback (default 90)
Global Flags:
-c, --config string       The saucectl config (default "~/.sauced.yaml")
--disable-telemetry   Disable sending telemetry data to OpenSauced
-l, --log-level string    The logging level. Options: error, warn, info, debug (default "info")
-o, --output string       The formatting for command output. One of: (table, yaml, csv, json) (default "table")
--tty-disable         Disable log stylization. Suitable for CI/CD and …
```
> fix: mark endpoint and beta flags as hidden

- .github/workflows/release.yaml
Adds npm caching to release workflow to speed up CI/CD.
Closes #121
N/A
N/A
> chore: added npm caching to release workflow to speed up CI/CD

- .sauced.yaml
Adds @zeucapua to the .sauced.yaml
Closes #138
N/A
> chore: added Zeu to the .sauced.yaml

- .github/workflows/pizza.yml
adds the [pizza-action](https://github.com/open-sauced/pizza-action) GitHub action to the project.
This will allow us to update the CODEOWNERS file on a weekly cadence on Sunday night's at midnight UTC.
Closes #140
N/A
This can only be tested once merged, but we've already enabled it on the open-sauced/app repository, and the repository settings already allow GitHub actions to create pull requests, so this should be all set to go.
> chore: adds the pizza-action GitHub action to the project

- cmd/generate/codeowners/output.go
- cmd/generate/codeowners/output_test.go
- pkg/config/spec.go
- Adds the `attribution-fallback` option to the `.sauced.yaml` file
- When generating a codeowners file, if no attributions are found, the attribution fallback entries are used
TODO
Closes #116 
1. Run `just build`
2. Add some fallback attributions to the `.sauced.yaml` for a repository, and optionally remove all known attributions
3. Generate the codeowners file with no primary attributions
4. Note the codeowners file is generated with the fallback attributions for each file
> feat: support fallback attributions when generating codeowners file

- cmd/generate/config/config.go
- pkg/utils/posthog.go
- telemetry.go
Implements the following events for `pizza generate config` command to be captured on PostHog
- `pizza_cli_generated_config`: on successful generation
- `pizza_cli_failed_to_generate_config`: on failure
- `pizza_cli_generated_config_mode`: logs whether the user is in 'automatic' or 'interactive' mode
Closes #187
> feat: implement PostHog captures for `generate config`

- npm/package.json
Cuts a 2.0.0 release
N/a
N/a
N/a
> feat: Cut 2.0.0 release

- cmd/generate/config/config.go
Implements a check to ignore any contributors with '[bot]' in its name.
Closes #172 
1. Build the program
2. Use the `pizza generate config` command
3. Check that no '[bot]' accounts are attributed automatically
4. OR no email with '[bot]' are shown during interactive mode
> feat: ignore [bot] named contributors for `pizza generate config`
